spring:

  jackson:
    serialization:
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: blang_board

flyway:
  baseline-on-migrate: true