---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
  - name: repo

outputs:
  - name: artifacts

run:
  path: repo/ci/scripts/push.sh

caches:
  - path: .gradle/
  - path: .m2/
