---
platform: linux

image_resource:
  type: docker-image
  source: {repository: codequest/ruby-golang-java-nodejs}

inputs:
  - name: repo

outputs:
  - name: artifacts

run:
  path: repo/ci/scripts/push.sh
