---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jghiloni/spring-boot-rootfs
    tag: 2.0-latest

inputs:
  - name: repo

outputs:
  - name: artifacts

run:
  path: repo/ci/scripts/push.sh

caches:
  - path: .gradle/
  - path: .m2/
